# Copyright 2025 the samurai team
# SPDX-License-Identifier:  BSD-3-Clause
"""
Exact solution of the one-dimensional Riemann problem for an ideal gas.

The shock tube cases are checked against this. A convergence order says how
fast an error decays; this says where the shock, the contact and the
rarefaction are.

The algorithm is the classical one of

    E.F. Toro, "Riemann Solvers and Numerical Methods for Fluid Dynamics.
    A Practical Introduction", 3rd ed., Springer, 2009,
    https://doi.org/10.1007/b79761

chapter 4: the star pressure solves the pressure-function equation

    f_L(p) + f_R(p) + (u_R - u_L) = 0,

f_K being the shock (Rankine-Hugoniot) branch for p > p_K and the rarefaction
(isentropic) branch for p <= p_K. It is solved by Newton iterations from the
two-rarefaction guess, then the solution is sampled at a given x/t.

Run the module to reproduce the star states of Toro's Table 4.3:

    python exact_riemann.py
"""

import numpy as np

__all__ = ["star_state", "sample", "solution"]


def _f(p, rho_k, p_k, gamma):
    """Toro eq. (4.6)-(4.7): pressure function of one side, and its derivative."""
    a_k = np.sqrt(gamma * p_k / rho_k)

    if p > p_k:  # shock
        A = 2.0 / ((gamma + 1.0) * rho_k)
        B = (gamma - 1.0) / (gamma + 1.0) * p_k
        root = np.sqrt(A / (B + p))
        return (p - p_k) * root, root * (1.0 - 0.5 * (p - p_k) / (B + p))

    # rarefaction
    ratio = p / p_k
    power = (gamma - 1.0) / (2.0 * gamma)
    return (
        2.0 * a_k / (gamma - 1.0) * (ratio**power - 1.0),
        1.0 / (rho_k * a_k) * ratio ** (-(gamma + 1.0) / (2.0 * gamma)),
    )


def star_state(left, right, gamma=1.4, tol=1e-14, maxiter=100):
    """Pressure and velocity of the star region between the two states.

    `left` and `right` are (rho, u, p) triples. Raises if the two states have
    already produced a vacuum, which is the case the iteration cannot solve
    (Toro sec. 4.3.3, pressure positivity condition).
    """
    rho_l, u_l, p_l = left
    rho_r, u_r, p_r = right
    a_l = np.sqrt(gamma * p_l / rho_l)
    a_r = np.sqrt(gamma * p_r / rho_r)

    du = u_r - u_l
    if 2.0 / (gamma - 1.0) * (a_l + a_r) <= du:
        raise ValueError("vacuum generated by the initial data; no star state")

    # two-rarefaction guess (Toro eq. 4.46), always positive
    power = (gamma - 1.0) / (2.0 * gamma)
    p = (
        (a_l + a_r - 0.5 * (gamma - 1.0) * du)
        / (a_l / p_l**power + a_r / p_r**power)
    ) ** (1.0 / power)

    for _ in range(maxiter):
        f_l, df_l = _f(p, rho_l, p_l, gamma)
        f_r, df_r = _f(p, rho_r, p_r, gamma)
        step = (f_l + f_r + du) / (df_l + df_r)
        p_new = max(p - step, tol)
        if abs(p_new - p) / (0.5 * (p_new + p)) < tol:
            p = p_new
            break
        p = p_new
    else:
        raise RuntimeError("the star pressure iteration did not converge")

    f_l, _ = _f(p, rho_l, p_l, gamma)
    f_r, _ = _f(p, rho_r, p_r, gamma)
    return p, 0.5 * (u_l + u_r + f_r - f_l)


def _sample_side(s, state, p_star, u_star, gamma, mirror):
    """Sample the side of the contact the ray s falls on.

    Written once for both sides. `mirror` is +1 on the left and -1 on the right:
    negating x and u turns the right state into a left one, so the left-running
    wave formulas of Toro sec. 4.5 serve both, which is all his two symmetric
    sampling branches say.
    """
    rho_k, u_k, p_k = state
    a_k = np.sqrt(gamma * p_k / rho_k)

    s, u_k, u_star = mirror * s, mirror * u_k, mirror * u_star
    ratio = p_star / p_k

    if p_star > p_k:  # shock, Toro eq. (4.52)-(4.53)
        beta = (gamma - 1.0) / (gamma + 1.0)
        speed = u_k - a_k * np.sqrt((gamma + 1.0) / (2.0 * gamma) * ratio + (gamma - 1.0) / (2.0 * gamma))
        if s <= speed:
            return rho_k, mirror * u_k, p_k
        return rho_k * (ratio + beta) / (beta * ratio + 1.0), mirror * u_star, p_star

    # rarefaction, Toro eq. (4.55)-(4.56)
    a_star = a_k * ratio ** ((gamma - 1.0) / (2.0 * gamma))
    head, tail = u_k - a_k, u_star - a_star
    if s <= head:
        return rho_k, mirror * u_k, p_k
    if s >= tail:
        return rho_k * ratio ** (1.0 / gamma), mirror * u_star, p_star

    # inside the fan
    u = 2.0 / (gamma + 1.0) * (a_k + 0.5 * (gamma - 1.0) * u_k + s)
    a = 2.0 / (gamma + 1.0) * (a_k + 0.5 * (gamma - 1.0) * (u_k - s))
    return (
        rho_k * (a / a_k) ** (2.0 / (gamma - 1.0)),
        mirror * u,
        p_k * (a / a_k) ** (2.0 * gamma / (gamma - 1.0)),
    )


def sample(s, left, right, p_star, u_star, gamma=1.4):
    """State (rho, u, p) on the ray x/t = s."""
    if s <= u_star:
        return _sample_side(s, left, p_star, u_star, gamma, +1)
    return _sample_side(s, right, p_star, u_star, gamma, -1)


def solution(x, t, left, right, x0=0.5, gamma=1.4):
    """The exact solution at time t on the points x, as (rho, u, p) arrays."""
    p_star, u_star = star_state(left, right, gamma)
    s = (np.asarray(x, dtype=float) - x0) / t
    out = np.array([sample(si, left, right, p_star, u_star, gamma) for si in s])
    return out[:, 0], out[:, 1], out[:, 2]


# ---------------------------------------------------------------------------
# Self test
# ---------------------------------------------------------------------------
# The five shock tubes of Toro's Table 4.1, with the star states of his Table
# 4.3. Reproducing them is what makes this module usable as a reference. The
# values are kept as the book prints them, and the comparison only asks for the
# digits it actually printed: one unit of the last one, or six significant
# digits, whichever is looser. Test 5 needs the second bound, its initial data
# being the star state of tests 3 and 4 as the book rounded it before reusing
# it.
TORO_TESTS = {
    1: ((1.0, 0.0, 1.0), (0.125, 0.0, 0.1), "0.30313", "0.92745"),
    2: ((1.0, -2.0, 0.4), (1.0, 2.0, 0.4), "0.00189", "0.00000"),
    3: ((1.0, 0.0, 1000.0), (1.0, 0.0, 0.01), "460.894", "19.5975"),
    4: ((1.0, 0.0, 0.01), (1.0, 0.0, 100.0), "46.0950", "-6.19633"),
    5: ((5.99924, 19.5975, 460.894), (5.99242, -6.19633, 46.0950), "1691.64", "8.68975"),
}


def _printed_tolerance(text):
    """How far from a published value a value may sit and still match it."""
    decimals = len(text.split(".")[1]) if "." in text else 0
    return max(10.0**-decimals, 5e-6 * abs(float(text)))


def _self_test():
    print(f"{'test':>4}  {'p* (Toro)':>10} {'p* (here)':>14}  {'u* (Toro)':>10} {'u* (here)':>14}")
    ok = True
    for number, (left, right, p_ref, u_ref) in TORO_TESTS.items():
        p_star, u_star = star_state(left, right)
        print(f"{number:>4}  {p_ref:>10} {p_star:>14.6g}  {u_ref:>10} {u_star:>14.6g}")
        ok &= abs(p_star - float(p_ref)) <= _printed_tolerance(p_ref)
        ok &= abs(u_star - float(u_ref)) <= _printed_tolerance(u_ref)
    print("\nagrees with Table 4.3 to the printed digits" if ok else "\nDOES NOT agree with Table 4.3")
    return ok


if __name__ == "__main__":
    import sys

    sys.exit(0 if _self_test() else 1)
